### ISSUE TITLE
AmazonS3 connector does not support creating a bucket in a region other than us-east-1

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/connectors#102]
**Steps**
Invoke the createBucket request as specified in the below link with the region "us-west-1"
https://github.com/ballerinalang/connectors/tree/master/amazons3/docs/amazons3

**Issue**
The following error will be logged. Users won't be able to create buckets with any region other than us-east-1.
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
   <Code>AuthorizationHeaderMalformed</Code>
   <Message>The authorization header is malformed; the region 'us-west-1' is wrong; expecting 'us-east-1'</Message>
   <Region>us-east-1</Region>
   <RequestId>EEF62E14F311AB7F</RequestId>
   <HostId>Aukgpl8NlxhC5riJjRDulIYWSo/rEmdTibAXJxDa1onkKKPLEe9y5OtEzSmELQ7VWmkAf8h0hZw=</HostId>
</Error>
```

Follow the API [1] for more information.
[1] http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#create-bucket-intro

**Comment by Biruntha** [comment]
The amazon account may only paid/allowed to create in "us-west-1" only. Please check the account.

**Comment by dilinisg** [comment]
@Biruntha - We can select any region when we try to create a bucket from the S3 console.

**Comment by muthulee** [comment]
We no longer maintain this connector.
