### ISSUE TITLE
Screenscraping connector

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-lang/connectors#136]
I have this scenario that I need to implement:
1. I am managing girls' club for my daughter,
2. The club is using an online system that (behind username/password authentication) has a web page with the list of participants,
3. When someone new joins the club, the names get added to the list,
4. I need an application to (periodically) log into the website, download & parse the html, and if new members are found send them a welcome email.

From my perspective, this is a very valid scenario: today and for a long foreseeable future there will still be a lot of companies exposing data on web pages and not via proper APIs, and if Ballerina made such webpage-to-API translation easy - that would have been great.

**Comment by muthulee** [comment]
We will keep in connector roadmap.
