### ISSUE TITLE
Wordpress connector

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-lang/connectors#137]
I really need a Wordpress connector to automate incident and maintenance announcement publications.

Right now we have a form that engineers fill out when there is an incident, when the incident gets resolved, and then when post-mortem analysis is ready. The form kicks a script that sends the corresponding announcement to all paying customers.

What I would like to do is take it a step further and also publish the data in our wordpress blog (and Twitter account). We want to be as transparent with our service as possible.

So I would need to be able to:
1. Create a blog post,
2. Set category, title, body,
3. Publish the post and get the ID,
4. When new data becomes available, update the blog post with the new Title and new Body.

**Comment by malakasilva** [comment]
Will consider this as our next road map item.

**Comment by muthulee** [comment]
We will keep it in RRT roadmap.

**Comment by muthulee** [comment]
We will keep this in RRT roadmap
