### ISSUE TITLE
[Blocker] [Soap] execution fails on constructSoapRequest function 

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/connectors#140]
With the latest xml changes the $subject is happening on the following line

`xmls:addElementWithNamespace(soapRequest, "/soapenv:Envelope/soapenv:Header", value, n)`

This is directly affecting the salesforcesoap connector actions

**Comment by kesavany** [comment]
Fixed in Ballerina [1] Please check.
[1] - https://github.com/ballerinalang/ballerina/pull/2643

**Comment by muthulee** [comment]
We are not maintaining SOAP connector. It will be a new impl.
