### ISSUE TITLE
salesforcesoap/samples.bal should be updated to cater to 0.89 v

### ISSUE THREAD

**Issue by ushanib** [ballerina-lang/connectors#156]
The below sample should be updated according to 0.89v
https://github.com/ballerinalang/connectors/blob/master/salesforcesoap/samples/salesforcesoap/samples.bal

        xml queryOptions = `<urn:QueryOptions xmlns:urn="urn:partner.soap.sforce.com"><urn:batchSize>200</urn:batchSize></urn:QueryOptions>`; are no longer valid.

should be changed as 

		xml queryOptions = xmls:parse("<urn:QueryOptions xmlns:urn=\"urn:partner.soap.sforce.com\"><urn:batchSize>1</urn:batchSize></urn:QueryOptions>");

**Comment by muthulee** [comment]
It is already updated
