### ISSUE TITLE
Send WS-Security header with Soap Connector

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/connectors#181]
Currently for the available actions constructSoapRequest and send, both is taking xml[] as headers. But when it comes to WS-Security (a sample given below) there are some additional fields that has to be injected from the connector itself (has to act according to the spec) and it's not right to expect the developer to configure those. 

**Sample ws-security header**
```
 <wsse:Security>
      <wsse:UsernameToken>
        <wsse:Username>NNK</wsse:Username>
        <wsse:Password Type="...#PasswordDigest">weYI3nXd8LjMNVksCKFV8t3rgHh3Rw==</wsse:Password>
        <wsse:Nonce>WScqanjCEAC4mQoBE07sAQ==</wsse:Nonce>
        <wsu:Created>2003-07-16T01:24:32</wsu:Created>
      </wsse:UsernameToken>
    </wsse:Security>
```

**Comment by muthulee** [comment]
We are not maintaining SOAP connector. It will be a new impl.
