### ISSUE TITLE
[FB] why link and place are mandatory for 'create post' operation?

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerina-lang/connectors#184]
As per [1], four parameters are passed for 'Create Post' operation: id, msg, link and place.
IMO, link and place should be optional parameters for creating a post.

Referred [2] and I was able to create a post with only id and message.

Tried to pass only 2 parameters as below:
`facebookConnector.createPost(<id>, <message>);`

and got error:
`undefined action 'createPost' in connector 'org.wso2.ballerina.connectors.facebook:ClientConnector'`

[1] https://github.com/ballerinalang/connectors/tree/master/facebook/docs/facebook
[2] https://developers.facebook.com/docs/pages/publishing/

**Comment by muthulee** [comment]
We are not maintaining FB connector anymore
