### ISSUE TITLE
Typo on twitter EP

### ISSUE THREAD

**Issue by maheeka** [ballerina-lang/connectors#189]
TweeterEP is wrong and should be Twitter EP.

https://github.com/ballerinalang/connectors/blob/ff19ae1c77ddf59deae9b3ab9a9ffb4a63a40040/twitter/src/org/wso2/ballerina/connectors/twitter/ClientConnector.bal#L14

**Comment by maheeka** [comment]
@Biruntha  can you please check?

Also what is the reason to avoid the API version in the connector URL and have it appended in invocations? 

https://github.com/ballerinalang/connectors/blob/ff19ae1c77ddf59deae9b3ab9a9ffb4a63a40040/twitter/src/org/wso2/ballerina/connectors/twitter/ClientConnector.bal#L60

**Comment by maheeka** [comment]
Another question, can't we reuse the authorization header? Is it needed to create oauth header everytime an invocation is made?

**Comment by muthulee** [comment]
Closing issue creating a new one for Auth header. https://github.com/wso2-ballerina/package-twitter/issues/14
