### ISSUE TITLE
 Ballerina Connectors need proper versioning 

### ISSUE THREAD

**Issue by thariyarox** [ballerina-lang/connectors#66]
Currently in the connectors, we have not done versioning.

An example is facebook connector [1] calls the FB API 2.8. In future, when FB releases API 2.9, we might need to write a new connector.

So it is better to add a version in the package structure itself rather than depending on GIT releases.

Discussed the same on the DEV group in thread "Ballerina Connectors need proper versioning"

**Comment by muthulee** [comment]
Ack. We are working on it.
